module GlobalConstants

  ATM_BLANKET_ENDORSEMENTS = [
                'Blanket Additional Insured - Ongoing Operations included',
                'Blanket Additional Insured - Completed Ops - Commercial Work Only $250',
                'Blanket Additional Insured - Completed Ops - Commercial Work Only plus Blanket Waiver of Subrogation $400',
                'Blanket Additional Insured - Completed Ops - Commercial Work Only plus Blanket Primary Wording $400',
                'Blanket Additional Insured - Completed Ops - Commercial Work Only plus Blanket Primary Wording plus Blanket Waiver of Subrogation $500',
                'Blanket Primary Wording Endorsement $250',
                'Blanket Waiver of Subrogation Endorsement $250',
                'Blanket Primary Wording plus Blanket Waiver of Subrogation $400',
                'No Blanket'
  ]

  ATM_CLASS_CODES = Array[
                [99975,"99975 WINDOW CLEANING"],
                [99948,"99948 WATER SOFTENING EQUIPMENT – INSTALLATION, SERVICING OR REPAIR"],
                [99938,"99938 WAREHOUSES – NOC"],
                [99827,"99827 UPHOLSTERING – SHOP ONLY"],
                [99793,"99793 TRUCKERS"],
                [99777,"99777 TREE PRUNING, DUSTING, SPRAYING, REPAIRING, TRIMMING OR FUMIGATING"],
                [99746,"99746 TILE, STONE, MARBLE, MOSAIC OR TERRAZZO WORK – INTERIOR CONSTRUCTION"],
                [99650,"99650 TELEVISION OR RADIO RECEIVING SET INSTALLATION OR REPAIR"],
                [99505,"99505 SWIMMING POOL SERVICING"],
                [99303,"99303 STREET CLEANING (NO SNOW REMOVAL)"],
                [99080,"99080 SOLAR ENERGY CONTRACTORS"],
                [99004,"99004 SIGN PAINTING OR LETTERING ON BUILDINGS OR STRUCTURES"],
                [99003,"99003 SIGN PAINTING OR LETTERING – INSIDE OF BUILDINGS"],
                [98993,"98993 SIGN ERECTION, INSTALLATION OR REPAIR"],
                [98967,"98967 SIDING INSTALLATION"],
                [98884,"98884 SHEET METAL WORK – OUTSIDE"],
                [98806,"98806 SEPTIC TANK SYSTEMS – INSTALLATION, SERVICING OR REPAIR"],
                [98805,"98805 SEPTIC TANK SYSTEMS – CLEANING"],
                [98677,"98677 ROOFING – COMMERCIAL"],
                [98678,"98678 ROOFING – RESIDENTIAL"],
                [98502,"98502 PREFABRICATED BUILDING ERECTION"],
                [98483,"98483 PLUMBING – RESIDENTIAL OR DOMESTIC"],
                [98482,"98482 PLUMBING – COMMERCIAL AND INDUSTRIAL"],
                [98449,"98449 PLASTERING OR STUCCO WORK"],
                [43470,"43470 PEST CONTROL SERVICES"],
                [98344,"98344 PAPERHANGING"],
                [98308,"98308 PAINTING – SHOP ONLY"],
                [98305,"98305 PAINTING – INTERIOR – BUILDINGS OR STRUCTURES"],
                [98304,"98304 PAINTING – EXTERIOR – BUILDINGS OR STRUCTURES – 3 STORIES OR LESS IN HEIGHT"],
                [98111,"98111 OFFICE MACHINES OR APPLIANCES – INSTALLATION, INSPECTION, ADJUSTMENT, REPAIR"],
                [97222,"97222 MACHINERY OR EQUIPMENT – INDUSTRIAL – INSTALLATION, SERVICING OR REPAIR"],
                [97653,"97653 METAL ERECTION – NONSTRUCTURAL – NOC"],
                [97650,"97650 METAL ERECTION – DECORATIVE OR ARTISTIC"],
                [97652,"97652 METAL ERECTION – IN THE CONSTRUCTION OF DWELLINGS NOT EXCEEDING 2 STORIES IN HEIGHT"],
                [97447,"97447 MASONRY"],
                [97111,"97111 LOGGING AND LUMBERING (OVERCUT EXCLUSION MANDATORY)"],
                [97050,"97050 LAWN CARE SERVICES"],
                [97047,"97047 LANDSCAPE GARDENING"],
                [96816,"96816 JANITORIAL SERVICES (No Floor Waxing)"],
                [96611,"96611 INTERIOR DECORATORS"],
                [96409,"96409 INSULATION WORK – ORGANIC OR PLASTIC IN SOLID STATE"],
                [96408,"96408 INSULATION WORK – PLASTIC – NOC"],
                [96053,"96053 HOUSE FURNISHINGS INSTALLATION – NOC"],
                [95647,"95647 HEATING OR COMBINED HEATING AND AIR CONDITIONING SYSTEMS OR EQUIPMENT - DEALERS OR DISTRIBUTORS AND INSTALLATION, SERVICEING OR REPAIR- NO LPG"],
                [95625,"95625 HANDYPERSON"],
                [95410,"95410 GRADING OF LAND"],
                [13590,"13590 GLASS DEALERS AND GLAZIERS"],
                [95233,"95233 GARBAGE, ASH OR REFUSE COLLECTING"],
                [95124,"95124 FURNITURE OR FIXTURES – INSTALLATION IN OFFICES OR STORES – PORTABLE – METAL OR WOOD"],
                [94569,"94569 FLOOR COVERING INSTALLATION – NOT CERAMIC TILE OR STONE"],
                [94276,"94276 FENCE ERECTION CONTRACTORS"],
                [94007,"94007 EXCAVATION"],
                [92478,"92478 ELECTRICAL WORK – WITHIN BUILDINGS"],
                [92451,"92451 ELECTRICAL APPARATUS – INSTALLATION, SERVICING OR REPAIR – NOC"],
                [94381,"94381 FIRE SUPPRESSION SYSTEMS – INSTALLATION, SERVICING OR REPAIR ($2,000 MP)"],
                [92338,"92338 DRY WALL OR WALLBOARD INSTALLATION"],
                [92215,"92215 DRIVEWAY, PARKING AREA OR SIDEWALK – PAVING OR REPAVING"],
                [91746,"91746 DOOR, WINDOW OR ASSEMBLED MILLWORK – INSTALLATION – METAL"],
                [91629,"91629 DEBRIS REMOVAL – CONSTRUCTION SITE"],
                [91590,"91590 CONTRACTORS PERMANENT YARDS – MAINTENANCE OR STORAGE OF EQUIPMENT OR MATERIAL"],
                [91560,"91560 CONCRETE CONSTRUCTION"],
                [91551,"91551 COMMUNICATION EQUIPMENT INSTALLATION – INDUSTRIAL OR COMMERCIAL"],
                [91523,"91523 CLEANING – OUTSIDE SURFACES OF BUILDINGS"],
                [91481,"91481 CHIMNEY CLEANING"],
                [91436,"91436 CEILING OR WALL INSTALLATION – METAL"],
                [91405,"91405 CARPET, RUG, FURNITURE OR UPHOLSTERY CLEANING – ON CUSTOMER’S PREMISES"],
                [91343,"91343 CARPENTRY – SHOP ONLY"],
                [91580,"91580 CONTRACTORS EXECUTIVE SUPERVISORS"],
                [91342,"91342 CARPENTRY – NOC"],
                [91341,"91341 CARPENTRY – INTERIOR"],
                [91340,"91340 CARPENTRY – CONSTRUCTION OF RESIDENTIAL PROPERTY NOT EXCEEDING THREE STORIES IN HEIGHT"],
                [91315,"91315 CABLE OR SUBSCRIPTION TELEVISION COMPANIES"],
                [91179,"91179 AUCTIONS – ON PREMISES OWNED OR RENTED BY THE INSURED"],
                [91177,"91177 AUCTIONEERS – SALES CONDUCTED AWAY FROM THE INSUREDS PREMISES"],
                [91155,"91155 APPLIANCES AND ACCESSORIES – INSTALLATION, SERVICING OR REPAIR – HOUSEHOLD"],
                [91150,"91150 APPLIANCES AND ACCESSORIES – INSTALLATION, SERVICING OR REPAIR – COMMERCIAL"],
                [91127,"91127 ALARMS AND ALARM SYSTEMS – INSTALLATION, SERVICING OR REPAIR"],
                [91111,"91111 AIR CONDITIONING SYSTEMS OR EQUIPMENT – DEALERS OR DISTRIBUTORS AND INSTALLATION, SERVICING OR REPAIR"],
                [10010,"10010 AIR CONDITIONING EQUIPMENT – DEALERS OR DISTRIBUTORS ONLY"],
                [90089,"90089 ADVERTISING SIGN COMPANIES – OUTDOOR"]].freeze

  ATM_STATES = Array[ ["AK", "Alaska"],
                ["AL", "Alabama"],
                ["AZ", "Arizona"],
                ["CA", "California"],
                ["FL", "Florida"],
                ["GA", "Georgia"],
                ["IL", "Illinois"],
                ["KS", "Kansas"],
                ["MN", "Minnesota"],
                ["NJ", "New Jersey"],
                ["NM", "New Mexico"],
                ["OH", "Ohio"],
                ["OR", "Oregon"],
                ["PA", "Pennsylvania"],
                ["TN", "Tennessee"],
                ["TX", "Texas"],
                ["WA", "Washington"]].freeze

  US_STATES = Array[ ["AK", "Alaska"],
                ["AL", "Alabama"],
                ["AR", "Arkansas"],
                ["AS", "American Samoa"],
                ["AZ", "Arizona"],
                ["CA", "California"],
                ["CO", "Colorado"],
                ["CT", "Connecticut"],
                ["DC", "District of Columbia"],
                ["DE", "Delaware"],
                ["FL", "Florida"],
                ["GA", "Georgia"],
                ["GU", "Guam"],
                ["HI", "Hawaii"],
                ["IA", "Iowa"],
                ["ID", "Idaho"],
                ["IL", "Illinois"],
                ["IN", "Indiana"],
                ["KS", "Kansas"],
                ["KY", "Kentucky"],
                ["LA", "Louisiana"],
                ["MA", "Massachusetts"],
                ["MD", "Maryland"],
                ["ME", "Maine"],
                ["MI", "Michigan"],
                ["MN", "Minnesota"],
                ["MO", "Missouri"],
                ["MS", "Mississippi"],
                ["MT", "Montana"],
                ["NC", "North Carolina"],
                ["ND", "North Dakota"],
                ["NE", "Nebraska"],
                ["NH", "New Hampshire"],
                ["NJ", "New Jersey"],
                ["NM", "New Mexico"],
                ["NV", "Nevada"],
                ["NY", "New York"],
                ["OH", "Ohio"],
                ["OK", "Oklahoma"],
                ["OR", "Oregon"],
                ["PA", "Pennsylvania"],
                ["PR", "Puerto Rico"],
                ["RI", "Rhode Island"],
                ["SC", "South Carolina"],
                ["SD", "South Dakota"],
                ["TN", "Tennessee"],
                ["TX", "Texas"],
                ["UT", "Utah"],
                ["VA", "Virginia"],
                ["VI", "Virgin Islands"],
                ["VT", "Vermont"],
                ["WA", "Washington"],
                ["WI", "Wisconsin"],
                ["WV", "West Virginia"],
                ["WY", "Wyoming"] ].freeze

end
