module GlobalConstants
  ATM_BLANKET_ENDORSEMENTS = [
                'Blanket Additional Insured - Ongoing Operations included',
                'Blanket Additional Insured - Completed Ops - Commercial Work Only $250',
                'Blanket Additional Insured - Completed Ops - Commercial Work Only plus Blanket Waiver of Subrogation $400',
                'Blanket Additional Insured - Completed Ops - Commercial Work Only plus Blanket Primary Wording $400',
                'Blanket Additional Insured - Completed Ops - Commercial Work Only plus Blanket Primary Wording plus Blanket Waiver of Subrogation $500',
                'Blanket Primary Wording Endorsement $250',
                'Blanket Waiver of Subrogation Endorsement $250',
                'Blanket Primary Wording plus Blanket Waiver of Subrogation $400',
                'No Blanket'
  ]
  US_STATES = Array[ ["AK", "Alaska"],
                ["AL", "Alabama"],
                ["AR", "Arkansas"],
                ["AS", "American Samoa"],
                ["AZ", "Arizona"],
                ["CA", "California"],
                ["CO", "Colorado"],
                ["CT", "Connecticut"],
                ["DC", "District of Columbia"],
                ["DE", "Delaware"],
                ["FL", "Florida"],
                ["GA", "Georgia"],
                ["GU", "Guam"],
                ["HI", "Hawaii"],
                ["IA", "Iowa"],
                ["ID", "Idaho"],
                ["IL", "Illinois"],
                ["IN", "Indiana"],
                ["KS", "Kansas"],
                ["KY", "Kentucky"],
                ["LA", "Louisiana"],
                ["MA", "Massachusetts"],
                ["MD", "Maryland"],
                ["ME", "Maine"],
                ["MI", "Michigan"],
                ["MN", "Minnesota"],
                ["MO", "Missouri"],
                ["MS", "Mississippi"],
                ["MT", "Montana"],
                ["NC", "North Carolina"],
                ["ND", "North Dakota"],
                ["NE", "Nebraska"],
                ["NH", "New Hampshire"],
                ["NJ", "New Jersey"],
                ["NM", "New Mexico"],
                ["NV", "Nevada"],
                ["NY", "New York"],
                ["OH", "Ohio"],
                ["OK", "Oklahoma"],
                ["OR", "Oregon"],
                ["PA", "Pennsylvania"],
                ["PR", "Puerto Rico"],
                ["RI", "Rhode Island"],
                ["SC", "South Carolina"],
                ["SD", "South Dakota"],
                ["TN", "Tennessee"],
                ["TX", "Texas"],
                ["UT", "Utah"],
                ["VA", "Virginia"],
                ["VI", "Virgin Islands"],
                ["VT", "Vermont"],
                ["WA", "Washington"],
                ["WI", "Wisconsin"],
                ["WV", "West Virginia"],
                ["WY", "Wyoming"] ].freeze
end
