default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: thrive_development
  username: root


test:
  <<: *default
  database: test

production:
  adapter: mysql2
  database: production
  url: <%= ENV['DATABASE_URL'] %>
  port: 3306
